jobs:
- job: Build
  displayName: 'Build and publish infrastructure artifacts'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    mainBicepPath: '$(System.DefaultWorkingDirectory)/infrastructure/bicep/main.bicep'
    bicepParameterFilesPath: '$(System.DefaultWorkingDirectory)/infrastructure/bicep/parameters'
    bicepArtifactsPath: '$(System.DefaultWorkingDirectory)/infrastructure/bicep'
  steps:
  - task: Bash@3
    displayName: 'Build Bicep templates'
    inputs:
      targetType: 'inline'
      script: |
        echo 'Building main bicep template'
        bicep build $(mainBicepPath)
  
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Bicep templates and parameters'
    inputs:
      targetPath: $(bicepArtifactsPath)
      artifact: 'bicep-artifacts'
      publishLocation: 'pipeline'
  
  