parameters:
- name: environmentName
  type: string
- name: serviceConnectionName
  type: string
- name: region
  type: string
- name: resourceGroupName
  type: string


stages:
- stage: 'Deploy${{ parameters.environmentName }}'
  displayName: 'Deploy'
  jobs:
  - deployment: 'DeployIntegrationInfrastrucutre${{ parameters.environmentName }}'
    displayName: 'Deploy Integration Infrastrucutre'
    pool:
      vmImage: 'ubuntu-latest'
    environment: '${{ parameters.environmentName }}'
    variables:
    - name: bicepArtifactName
      value: 'bicep-artifacts'
    - name: mainBicepPath
      value: $(Pipeline.Workspace)/$(bicepArtifactName)/02-main.bicep
    - name: mainParametersPath
      value: $(Pipeline.Workspace)/$(bicepArtifactName)/parameters/02-main.${{ parameters.environmentName }}.bicepparam
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Bicep templates and parameters'
            inputs:
              artifact: $(bicepArtifactName)
          
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy main Bicep template'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{ parameters.serviceConnectionName }}'
              resourceGroupName: '${{ parameters.resourceGroupName }}'
              csmFile: $(mainBicepPath)
              csmParametersFile: $(mainParametersPath)
              deploymentName: $(Build.BuildId)
              deploymentMode: 'Incremental'
              overrideParameters: '-buildId $(Build.BuildId)'
              location: '$(region)'
