parameters:
- name: environmentName
  type: string
- name: serviceConnectionName
  type: string
- name: region
  type: string
- name: resourceGroupName
  type: string
- name: dependencyName
  type: string
- name: parameters.functionAppName
  type: string

stages:
- stage: 'Deploy${{ parameters.environmentName }}'
  displayName: 'Deploy'
  dependsOn: ${{ parameters.dependencyName }}
  jobs:
  - deployment: 'DeployIntegrationInfrastrucutre${{ parameters.environmentName }}'
    displayName: 'Deploy Integration Infrastrucutre'
    pool:
      vmImage: 'ubuntu-latest'
    environment: '${{ parameters.environmentName }}'
    variables:
    - name: bicepArtifactName
      value: 'bicep-artifacts'
    - name: mainBicepPath
      value: $(Pipeline.Workspace)/$(bicepArtifactName)/main.bicep
    - name: mainParametersPath
      value: $(Pipeline.Workspace)/$(bicepArtifactName)/parameters/main.${{ parameters.environmentName }}.bicepparam
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Bicep templates and parameters'
            inputs:
              artifact: $(bicepArtifactName)
          
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy main Bicep template'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{ parameters.serviceConnectionName }}'
              resourceGroupName: '${{ parameters.resourceGroupName }}'
              csmFile: $(mainBicepPath)
              csmParametersFile: $(mainParametersPath)
              deploymentName: $(Build.BuildId)
              deploymentMode: 'Incremental'
              location: '$(region)'

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Function App Artifact'
            inputs:
              artifact: 'function-app-artifact'

          - task: AzureFunctionApp@1
            displayName: 'Deploy Azure Function'
            inputs:
              azureSubscription: '${{ parameters.serviceConnectionName }}'
              appType: 'functionApp'
              appName: '${{ parameters.functionAppName }}'
              package: '$(Pipeline.Workspace)/function-app-artifact/*.zip'
              deploymentMethod: 'auto'