trigger:
  branches:
    include:
    - 'main'

stages:
- stage: Build
  displayName: 'Build and publish infrastructure artifacts'
  jobs:
  - template: templates/psrule.yaml
    parameters:
      psRuleModules: 'PSRule.Rules.Azure,PSRule.Rules.CAF'
      psRuleBaseline: 'Azure.GA_2024_06'
  - template: 'templates/build.yaml'
    parameters:
      dependencyName: 'PSRule'

- template: 'templates/deploy.yaml'
  parameters:
    environmentName: 'dev'
    region: eastus2
    resourceGroupName: SLOC-POC2
    serviceConnectionName: 'CHHOUSE_FDPO'
    dependencyName: 'Build'
    functionAppName: 'ch-sloc-poc-loc-core-srq-func'
